spring.application.name=lifelink-backend
server.port=8080

# In-memory H2 profile with MySQL compatibility
spring.datasource.url=jdbc:h2:mem:lifelink_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.username=root
spring.datasource.password=Harini2815
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

lifelink.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
lifelink.jwt.expiration-ms=86400000
lifelink.seed.enabled=true
